### ISSUE TITLE
Recurring 500 Internal Server Error on Login via Google and Email

### ISSUE THREAD

**Issue by JonathanStefanov** [noahflk/railtrack#149]
### Description

I am encountering a persistent issue when attempting to sign in to the platform, regardless of whether I use Google or email for authentication. After completing the login process, I am redirected to the /dashboard page, but consistently receive a 500 internal server error. This issue has been replicated on both Safari and Google Chrome browsers.

### Steps to Reproduce

1. Navigate to the login page.
2. Attempt to sign in using Google or email.
3. Observe the redirection to the /dashboard page.
4. Encounter a 500 internal server error.

### Expected Behavior

I expect to successfully access the dashboard page after signing in.

### Actual Behavior

After the login attempt, I am redirected to the /dashboard page but am met with a 500 internal server error.

### Possible Cause

My hypothesis is that the login process is not fully completing, yet a token is still being issued and stored in my cookies. The presence of this potentially invalid token (`sb-jjkdpskxksywnvgazjtd-auth-token`) might be causing the application to attempt an automatic login, leading to the error.

### Additional Information

- **Browser:** Safari, Google Chrome
- **OS:** MacOS Sonoma 14.3
- **Screenshot:** : 
<img width="1437" alt="image" src="https://github.com/noahflk/railtrack/assets/38321403/5ab5e40f-b1a7-48c4-9b76-b174c12bbf84">

### Resolution Attempts

- Cleared browser cookies and cache.
- Tried accessing on different browsers (Safari and Google Chrome).

**Comment by JonathanStefanov** [comment]
I just tested it in localhost, there, I was able to successfully create a new user and go to the dashboard. When trying to log in with user I had created on railtrack.ch, I correctly had the "Invalid Credentials" error. No idea why it does not work like this on production though

**Comment by JonathanStefanov** [comment]
Resolved with PR #151

**Comment by JonathanStefanov** [comment]
Here are the logs
<img width="825" alt="image" src="https://github.com/noahflk/railtrack/assets/38321403/7c4ba1b5-022e-45f9-b0c9-fdf6db58acc3">

**Comment by noahflk** [comment]
Thanks for the heads up. Supabase recently changed the way you connect through Prisma and this broke it. Please reopen this if you still encounter any issues.

**Comment by JonathanStefanov** [comment]
Yes you fixed it ! Perfect :)
