### ISSUE TITLE
Add infinite scroll pagination to the all journeys view

### ISSUE THREAD

**Issue by noahflk** [noahflk/railtrack#16]
Both the mobile (`/src/components/all-journeys/JourneyCards.tsx`) and the desktop (`/src/components/all-journeys/JourneyTable.tsx`) view of this page still load all journeys in one go. This should be changed to an infinite scroll where a new page of journeys is loaded whenever the user scrolls far enough down.

**Comment by KarthikRaju391** [comment]
Hey @noahflk, can I have a try at this?

**Comment by noahflk** [comment]
@KarthikRaju391 yes, please :) Assigned you.

**Comment by KarthikRaju391** [comment]
I just wanted to make sure... to implement infinite scrolling, there should be some kind of virtual rendering right? So, we are rendering only the part of the screen that is being revealed?

**Comment by KarthikRaju391** [comment]
Hey @noahflk, I have set up the project but I don't see any pagination even in the desktop view. I see that in the code the `<TablePagination />` component is commented int he `<JourneyTable />` component. Can you help me with this?

**Comment by noahflk** [comment]
@KarthikRaju391 that's on me. I forgot that I didn't re-implement pagination on the desktop view after the last refactor. In that case I think it makes sense to add infinite scroll to both mobile and desktop. However, feel free to start with only one in case that's simpler :)

**Comment by KarthikRaju391** [comment]
@noahflk, right now I can either go with paginated infinite scroll or use a library like [react-virtualized](https://bvaughn.github.io/react-virtualized/#/components/List) or [react-window](https://react-window.vercel.app/#/examples/list/fixed-size)(lighter than react-virtualized) to implement a virtual list. Which one do you want me to implement?

**Comment by noahflk** [comment]
@KarthikRaju391 

I'd go with an infinite scroll and not pagination. Pagination would mean stepping through the individual pages like to: https://tailwindui.com/components/application-ui/navigation/pagination. But in terms of UX I prefer infinite scrolling where new elements are automatically loaded at the bottom.

I think the main thing is implementing the [infinite queries](https://tanstack.com/query/v4/docs/guides/infinite-queries) on the data fetching side. You can look at this [example](https://tanstack.com/query/v4/docs/examples/react/load-more-infinite-scroll). React Virtualized sounds like a good choice to then only render the elements of the list that are in view.

**Comment by KarthikRaju391** [comment]
Yes, that's what I wanted to confirm. I'll go with infinite queries.

**Comment by KarthikRaju391** [comment]
@noahflk, do you want the users to load more journeys with a click of a button or should it happen automatically when the user scrolls down?
I have it working with the button now. Let me know how it should be...

https://user-images.githubusercontent.com/67912316/207387023-292d9b59-bb28-414b-8ebf-ae4a58199fd4.mp4

**Comment by KarthikRaju391** [comment]
Also, I had to fetch the journeys in the `JourneyTable` component instead of the `JourneyList` component for this to work. Is that fine or do you want to have a look at it?

**Comment by noahflk** [comment]
@KarthikRaju391 looks nice 👀

It would be good to automatically load the journeys as the user scrolls down. You could use this library to trigger a new load: https://www.npmjs.com/package/react-intersection-observer

**Comment by noahflk** [comment]
> Also, I had to fetch the journeys in the `JourneyTable` component instead of the `JourneyList` component for this to work. Is that fine or do you want to have a look at it?

Makes sense 👍

**Comment by KarthikRaju391** [comment]
@noahflk, Yes, I have already set up `react-intersection-observer`. Although, it is not behaving as we want. I will try and look into that and let you know!

**Comment by KarthikRaju391** [comment]
Oh ok, I will let you know soon...

**Comment by KarthikRaju391** [comment]
@noahflk, the infinite scrolling seems to be working. I have to implement the same feature in the `JourneyCard` component still. I will complete that and submit the PR tomorrow. Is that fine?
https://user-images.githubusercontent.com/67912316/207419353-92ca8ed0-5ad0-469b-9bd6-23567defd7bf.mp4
