### ISSUE TITLE
When navigating from another page to the dashboard the map doesn't center on the content

### ISSUE THREAD

**Issue by noahflk** [noahflk/railtrack#62]
It only centers after manually reloading the page.

https://user-images.githubusercontent.com/82475733/206933070-2c9ac0e9-58b8-42ef-b81a-276d50fab0d6.mp4

**Comment by mocherfaoui** [comment]
I was able to fix this in two ways:
- by wrapping this https://github.com/noahflk/railtrack/blob/b0062c96c2bd830055b8b2619521a71065b94618/src/components/Map.tsx#L59-L69
in `useCallback` and use it with [`onLoad`](https://visgl.github.io/react-map-gl/docs/api-reference/map#onload)
- by using [`reuseMaps`](https://visgl.github.io/react-map-gl/docs/api-reference/map#reusemaps), the only problem with this solution is that Mapbox will remembers the last state of the map so if the user zoomed in/out or dragged the map it will remember that last position

**Comment by noahflk** [comment]
@mocherfaoui thank you! Just commited a fix using the `onLoad`
