### ISSUE TITLE
Trying to add non-first journey leads to "Journey not found"

### ISSUE THREAD

**Issue by justinxu421** [noahflk/railtrack#68]
When trying to add a journey that is not the 1st, a Journey not found appears, but selecting the first journey works.

https://user-images.githubusercontent.com/25185582/206963785-9d8c2df2-a14c-4af0-9202-66cd53838bd6.mov

**Comment by noahflk** [comment]
Thanks for finding this @justinxu421 !

It was some kind of edge-case where the API didn't return the desired connection on the server. Should be fixed with #9943934
