### ISSUE TITLE
When clicking the show earlier/later journey 5 new journeys should be appended/prepended

### ISSUE THREAD

**Issue by noahflk** [noahflk/railtrack#69]
* The journeys previously there should remain
* We always want to show 5 more newer/older journeys
* Behavior should be the same as here: https://www.sbb.ch/

**Comment by noahflk** [comment]
@justinxu421 should I assign this to you?

**Comment by justinxu421** [comment]
> @justinxu421 should I assign this to you?

Yes! I can take this
